name: Deploy Node.js Backend to Azure Web App - backend-tsn

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      # Skip build if you don't use TypeScript or Webpack
      - name: Prepare for Deployment
        run: |
          # Optional: Include any pre-deployment tasks here
          echo "Ready to deploy"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-tsn'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E77BCAEEE16547C2926E6D201A03A6F9 }}
